### PR TITLE
Only build for net6

### PR DESCRIPTION
**Pull request by N-lson**
Some of the latest dependencies only build for net6 (eg. Assent `2.1.0`) so dependabot PRs can't be merged.

[sc-32233]

### CODE REVIEW

**Review by tothegills — COMMENTED** [review]
Need more info. Why can we only build for net6.0 now?

**Comment by N-lson** [comment]
@tothegills 

>Some of the latest dependencies only build for net6 (eg. Assent 2.1.0) so dependabot PRs can't be merged.

netcoreapp3.1 is EOL. Is there a reason we need to support net framework for newer versions of this Caching library?

**Comment by tothegills** [comment]
> Is there a reason we need to support net framework for newer versions of this Caching library?
That's what I'm wondering too 😁

**Comment by N-lson** [comment]
I just realised Caching was consolidated into Server... https://github.com/OctopusDeploy/OctopusDeploy/pull/14463 I guess we can archive this repo???

**Pull request closed without merging**
